config/routes.rb
Rails.application.routes.draw do
  resources :materials, except: :show
  resources :products 
  root to: 'orders#index'
  resources :orders, except: :show do
    collection do
      get 'show_summary'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
    self.data = [
        { id: 1, name: '--' },
        { id: 2, name: '肉類・魚類・大豆製品' },
        { id: 3, name: '乳製品・海藻・小魚類' },
        { id: 4, name: '緑黄色野菜' },
        { id: 5, name: '淡色野菜・果物' },
        { id: 6, name: '穀類・芋類・砂糖' },
        { id: 7, name: '油脂類' },
        { id: 8, name: '調味料' },
        { id: 9, name: 'その他' }
    ]

    include ActiveHash::Associations
    has_many :materials
end

app/models/material.rb
class Material < ApplicationRecord
    extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to :category
    validates :image, presence: true
    validates :name, presence: true
    validates :category_id, numericality: { other_than: 1, message: 'を入力してください' }
    validates :quantity_unit, presence: true

    has_one_attached :image
    has_many :products, through: :product_materials
    has_many :product_materials
end

app/models/order.rb
class Order < ApplicationRecord
    validates :name, presence: true

    has_many :order_products, dependent: :destroy
    has_many :products, through: :order_products
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
    Max_Order_Products_Count = 5
    belongs_to :product
    belongs_to :order

    validate :limit_order_products_count

    private

    def limit_order_products_count
        errors.add(:base, "#{Max_Order_Products_Count}品までです") if order.products.count >= Max_Order_Products_Count
    end
end

app/models/product.rb
class Product < ApplicationRecord
    extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to :sort

    validates :image, presence: true
    validates :name, presence: true
    validates :sort_id, numericality: { other_than: 1, message: 'を入力してください' }

    has_one_attached :image
    has_many :product_materials, dependent: :destroy
    has_many :materials, through: :product_materials
    has_many :order_products, dependent: :destroy
    has_many :orders, through: :order_products
end

app/models/product_material.rb
class ProductMaterial < ApplicationRecord
    validates :single_quantity, numericality: true, allow_blank: true

    belongs_to :material
    belongs_to :product

    def save_single_quantity(product_material, single_quantity)
        product_material.single_quantity = single_quantity
        product_material.save
    end
end

app/models/sort.rb
class Sort < ActiveHash::Base
    self.data = [
        { id: 1, name: '--' },
        { id: 2, name: '主食' },
        { id: 3, name: '汁物' },
        { id: 4, name: '主菜' },
        { id: 5, name: '副菜' },
        { id: 6, name: 'その他' }
    ]

    include ActiveHash::Associations
    has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :basic_auth

    private

    def basic_auth
        authenticate_or_request_with_http_basic do |username, password|
            username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
        end
    end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
    before_action :set_material, only: [:edit, :update, :destroy]

    def index
        @materials = Material.all
    end

    def new
        @material = Material.new
    end

    def create
        @material = Material.new(material_params)
        if @material.save
            redirect_to action: :index
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @material.update(material_params)
            redirect_to action: :index
        else
            render :edit
        end
    end

    def destroy
        @material.destroy
        redirect_to action: :index
    end

    private

    def material_params
        params.require(:material).permit(:name, :image, :category_id, :quantity_unit, :options)
    end

    def set_material
        @material = Material.find(params[:id])
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :set_order, only: [:edit, :update, :destroy]
    before_action :set_product_all, only: [:new, :edit]

    def index
        @orders = Order.all
    end

    def new
        @order = Order.new
    end

    def create
        @order = Order.new(order_params)
        if @order.save
            redirect_to root_path
        else
            @products = Product.all
            render :new
        end
    end

    def edit
    end

    def update
        if @order.update(order_params)
            redirect_to root_path
        else
            @products = Product.all
            render :edit
        end
    end

    def destroy
        @order.destroy
        redirect_to root_path
    end

    def show_summary
        @orders = Order.includes(products: :materials, products: :product_materials)
    end

    private

    def order_params
        params.require(:order).permit(:name, product_ids: [])
    end

    def set_order
        @order = Order.find(params[:id])
    end

    def set_product_all
        @products = Product.all
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :set_product, only: [:show, :edit, :update, :destroy]
    before_action :set_material_all, only: [:new, :edit]

    def index
        @products = Product.all
    end

    def show
    end

    def new
        @product = Product.new
    end

    def create
        @product = Product.new(product_params)
        if @product.save
            @product.product_materials.each_with_index do |product_material, i|
                product_material.save_single_quantity(product_material, single_quantities_params[:single_quantities][i])
            end
            redirect_to action: :index
        else
            @materials = Material.all
            render :new
        end
    end

    def edit
        @product_materials = ProductMaterial.where(product_id: @product.id)
    end

    def update
        if @product.update(product_params)
            @product.product_materials.each_with_index do |product_material, i|
                product_material.save_single_quantity(product_material, single_quantities_params[:single_quantities][i])
            end
            redirect_to action: :show
        else
            @materials = Material.all
            @product_materials = @product.product_materials
            render :edit
        end
    end

    def destroy
        @product.destroy
        redirect_to action: :index
    end

    private

    def product_params
        params.require(:product).permit(:name, :image, :sort_id, :options, material_ids: [])
    end

    def single_quantities_params
        params.permit(single_quantities: [])
    end

    def set_product
        @product = Product.find(params[:id])
    end

    def set_material_all
        @materials = Material.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
    # 献立に使用されている食材と分量をそれぞれ配列に格納する
    def collect_materials(orders)
        materials = []
        quantities = {}
        orders.each do |order|
            order.products.each do |product|
                product.materials.each do |material|
                    materials << material
                    quantities[material.id] = 0 if quantities[material.id].nil?
                    quantities[material.id] += product.product_materials.select do |hash|
                                                    hash.material_id == material.id
                                                end [0].single_quantity
                end
            end
        end
        materials = materials.uniq
        [materials, quantities]
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
    <div class="error-alert">
        <ul>
            <% model.errors.full_messages.each do |message| %>
                <li class='error-message'><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>matelist</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <%= yield %>
    </body>
</html>

app/views/materials/_material_form.html.erb
<h2 class='material-sell-title'>食材の情報を入力</h2>
<div class='form-wrapper'>
    <%= form_with model: @material, local: true do |form| %>
    <%= render 'layouts/error_messages', model: @material %>
        <div class='img-upload'>
            <div class='guid-text'>
                食材画像
                <span class='indispensable'>（必須）</span>
            </div>
            <label class='click-upload'>
                <p class='upload-text'>画像をアップロード</p>
                <%= form.file_field :image, class: 'image-btn', id: 'material-image' %>
            </label>
        </div>
        <div class='guid-text'>
            食材名
            <span class='indispensable'>（必須）</span>
        </div>
        <%= form.text_field :name, class: 'material-text' %>
        <div class='guid-text'>
            基礎食品群
            <span class='indispensable'>（必須）</span>
        </div>
        <%= form.collection_select(:category_id, Category.all, :id, :name, {}, {class: 'material-text'}) %>
        <div class='guid-text'>
            分量の単位（必須)
        </div>
        <%= form.text_field :quantity_unit, class: 'material-text', placeholder: 'g, ml, 個, 合など' %>
        <div class='guid-text'>
            メモ
        </div>
        <%= form.text_area :options, class: 'material-options', placeholder: '255文字まで記述可能です' %>
        <div class='input-btn-contents'>
            <label class='input-post'>
                <% if params[:"action"] == "new" || params[:"action"] == "create" %>
                    <p class='post-text'>登録する</p>
                    <%= form.submit '登録する', class: 'input-btn' %>
                <% end %>
                <% if params[:"action"] == "edit" || params[:"action"] == "update" %>
                    <p class='post-text'>変更する</p>
                    <%= form.submit '変更する', class: 'input-btn' %>
                <% end %>
            </label>
        </div>
    <% end %>      
</div>

app/views/materials/edit.html.erb
<div class='catch-copy'>
  食材把握ツール
</div>
<div class='material-edit-header'>
  <div class='page-title'>食材の情報を編集する</div>
  <div class='header-btn-wrapper'>
    <a href="/materials" class='header-btn'>食材一覧へ戻る</a>
  </div>
</div>

<div class='material-form'>
  <%= render "material_form" %>
</div>

app/views/materials/index.html.erb
<div class='materials-index-header'>
  <div class='catch-copy'>
    食材把握ツール
  </div>
  <div class='materials-index-header-main'>
    <div class='materials-index-page-title'>
      食材一覧
    </div>
    <div class='materials-index-header-btns-wrapper'>
      <a href="/materials/new" class='materials-index-header-btn'>食材登録</a>
      <a href="/" class='materials-index-header-btn'>献立一覧</a>
      <a href="/products" class='materials-index-header-btn'>料理一覧</a>
      <a href="/orders/show_summary" class='materials-index-header-btn'>買い物リスト</a>
    </div>
  </div>
</div>
<div class='materials-display'>
  <%= render 'shared/materials_display' %>
</div>

app/views/materials/new.html.erb
<div class='catch-copy'>
  食材把握ツール
</div>
<div class='material-new-header'>
  <div class='page-title'>食材登録</div>
  <div class='header-btn-wrapper'>
    <a href="/materials" class='header-btn'>食材一覧へ戻る</a>
  </div>
</div>
<div class='material-form'>
  <%= render "material_form" %>
</div>

app/views/orders/_side_bar.html.erb
<div class='order-side-bar-header'>
  <div class='page-title'>
    <% if params[:"action"] == "new" || params[:"action"] == "create" %>
      <%= "献立を組み立てる" %>
    <% end %>
    <% if params[:"action"] == "edit" || params[:"action"] == "update" %>
      <%= "献立を編集する" %>
    <% end %>
  </div>
  <div class='header-btn-wrapper'>
    <a href='/' class='header-btn'>献立一覧<br>へ戻る</a>
  </div>
</div> 

<div class='form'>
  <% if params[:"action"] == "new" || params[:"action"] == "create" %>
    <h2 class='orders-sell-title'>情報を入力してください</h2>
  <% end %>
  <% if params[:"action"] == "edit" || params[:"action"] == "update" %>
    <h2 class='orders-sell-title'>内容を変更してください</h2>
  <% end %>
  <%= form_with(model: @order, local: true) do |form| %>
    <%= render 'layouts/error_messages', model: @order %>
    <div class='guid-text'>献立の名前 <span class='indispensable'>必須</span></div>
    <%= form.text_field :name, class:"input-order-name" %>
    <div class='guid-text'>献立 <span class='indispensable'>必須(最大5品)</span></div>
    <div class='pick-products'>
      <% 5.times do |i| %>
        <div class='product-name-box-on-side-bar' id='product-<%= i + 1 %>-name'></div>
        <input name='order[product_ids][]' type='hidden' class='input-product-form' 
        id='input-product-<%= i+1 %>' >
      <% end %>
    </div>
    <div class='input-btn-contents'>
      <label class='input-post'>
        <% if params[:"action"] == "new" || params[:"action"] == "create" %>
          <p class='post-text'>登録する</p>
          <%= form.submit '登録する', class: 'input-btn' %>
        <% end %>
        <% if params[:"action"] == "edit" || params[:"action"] == "update" %>
          <p class='post-text'>変更する</p>
          <%= form.submit '変更する', class: 'input-btn' %>
        <% end %>
      </label>
    </div>
  <% end %>
</div>

app/views/orders/edit.html.erb
<div class='wrapper'>
  <div class='side-bar'>
    <%= render 'side_bar' %> 
  </div>
  <div class='products-all'>
    <div class='guid-header'>
      献立に入れる料理の画像をクリックしてください
    </div>
    <div class='products-display'>
      <%= render 'shared/products_display' %>
    </div>
  </div>
</div>

app/views/orders/index.html.erb
<div class='top-page-catch-copy'>
  食材把握ツール
</div>
<div class='top-page-header'>
  <div class='app-title'>
    Matelist
  </div>
  <div class='top-page-header-btns-wrapper'>    
    <%= link_to '買い物リスト', show_summary_orders_path, class: 'top-page-header-btn' %>    
    <%= link_to '献立登録', new_order_path, class: 'top-page-header-btn' %>
    <%= link_to '料理一覧', products_path, class: 'top-page-header-btn' %>
    <%= link_to '食材一覧', materials_path, class: 'top-page-header-btn' %>
  </div>
</div>
<div class='top-page-orders-wrapper'>
  <% @orders.each do |order| %>
    <div class='order-wrapper'>
      <div class='order-name'>
        <%= order.name %>
      </div>
      <ul class='manipulate-order-btns-wrapper'>
        <li>
          <%= link_to '編集', edit_order_path(order.id), class:'edit-order' %>
        </li>
        <li class='destroy-order-wrapper'>
          <%= link_to '削除', order_path(order.id), method: :delete, data: { confirm: '削除しますか？' }, class:'destroy-order' %>
        </li>
      </ul>
      <% order.products.each do |product| %>
        <div class='top-page-product-wrapper'>
          <%= image_tag product.image.variant(resize: '200x200'), class:'product-image' if product.image.attached? %>
          <div class='product-name'>
            <%= product.name %>
          </div>
        </div>
      <% end %>  
    </div>
  <% end %> 
</div>

app/views/orders/new.html.erb
<div class='wrapper'>
  <div class='side-bar'>
    <%= render 'side_bar' %> 
  </div>
  <div class='products-all'>
    <div class='guid-header'>
      献立に入れる料理の画像をクリックしてください
    </div>
    <div class='products-display'>
      <%= render 'shared/products_display' %>
    </div>
  </div>
</div>

app/views/orders/show_summary.html.erb
<div class='orders-show-summary-header'>
  <div class='catch-copy'>
    必要な食材は以下の通りです
  </div>
  <div class='orders-show-summary-header-main'>
    <div class='orders-show-summary-title'>
      買い物リスト
    </div>
    <input type='number' class='input-number-of-people' id='input-number-of-people'>
    <div class='follow-text'>人分</div>
    <div class='orders-show-summary-header-btns-wrapper'>    
      <%= link_to '献立一覧', orders_path, class: 'orders-show-summary-header-btn' %>    
      <%= link_to '料理一覧', products_path, class: 'orders-show-summary-header-btn' %>
      <%= link_to '食材一覧', materials_path, class: 'orders-show-summary-header-btn' %>
    </div>
  </div>
</div>
<div class='orders-show-summary-info-wrapper'>
  <% materials_quantities = collect_materials(@orders) %>
  <% materials = materials_quantities[0] %>
  <% quantities = materials_quantities[1] %>
  <% for i in 2..9 do %>
    <div class='category-name'><%= Category.data[i - 1][:name] %></div>
    <div class='materials-wrapper'>
      <% materials.select{|material| material.category_id == i}.each do |material| %>
        <% quantity = quantities[material.id] %>
        <%= render partial: 'shared/material', locals: { material: material, quantity: quantity } %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/orders/tally.html.erb
<div class='catch-copy'>
</div>
<div class='order-tally-header'>
  <div class='order-tally-title'>
    買い物リスト
  </div>
  <div class='order-tally-header-btns-wrapper'>    
    <%= link_to '献立一覧', orders_path, class: 'order-tally-header-btn' %>    
    <%= link_to '料理一覧', products_path, class: 'order-tally-header-btn' %>
    <%= link_to '食材一覧', materials_path, class: 'order-tally-header-btn' %>
  </div>
</div>
<div class='order-tally-info-wrapper'>
  <% materials = [] %>
  <% quantities = {} %> 
  <% @orders.each do |order| %>
    <% order.products.each do |product| %>
      <% product.materials.each do |material| %>
        <% materials << material %>
        <% quantities[material.id] = 0 if quantities[material.id] == nil %>
        <% quantities[material.id] += product.product_materials.select{ |hash| hash.material_id == material.id }[0].single_quantity %>
      <% end %>
    <% end %>
  <% end %>
  <% materials = materials.uniq %>

  <% for i in 2..9 do %>
    <div class='category-name'><%= Category.data[i - 1][:name] %></div>
    <div class='materials-wrapper'>
      <% materials.select{|material| material.category_id == i}.each do |material| %>
        <%= render partial: 'shared/material', locals: { material: material, quantities: quantities } %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/products/_side_bar.html.erb
<div class='side-bar-header'>
  <div class='page-title'>
    <% if params[:"action"] == "new" || params[:"action"] == "create" %>
      <%= "料理を登録する" %>
    <% end %>
    <% if params[:"action"] == "edit" || params[:"action"] == "update" %>
      <%= "料理を編集する" %>
    <% end %>
  </div>
  <div class='side-header-btn-wrapper'>
    <a href="/products" class='side-header-btn'>料理一覧<br>へ戻る</a> 
  </div>
</div> 

<div class='form'>
  <% if params[:"action"] == "new" || params[:"action"] == "create" %>
    <h2 class='product-sell-title'>情報を入力してください</h2>
  <% end %>
  <% if params[:"action"] == "edit" || params[:"action"] == "update" %>
    <h2 class='product-sell-title'>情報を変更してください</h2>
  <% end %>
  <%= form_with(model: @product, local: true) do |form| %>
  <%= render 'layouts/error_messages', model: @product %>
    <div class='img-upload'>
      <div class='guid-text'>
        料理画像
        <span class='indispensable'>必須</span>
      </div>
      <label class='click-upload'>
        <p class='upload-text'>
          <p>画像をアップロード</p>
        <%= form.file_field :image, class: 'image-btn', id: 'material-image' %>
      </label>
    </div>
    <div class='guid-text'>
      料理名
      <span class='indispensable'>必須</span>
    </div>
    <%= form.text_field :name, class: 'input-form' %>
    <div class='guid-text'>
      分類
      <span class='indispensable'>必須</span>
    </div>
    <%= form.collection_select(:sort_id, Sort.all, :id, :name, {}, {class: 'input-form'}) %>
    <div class='guid-text'>
      使用する食材
    </div>
    <div id='pick-materials'>
      <% if params[:"action"] == "edit" || params[:"action"] == "update" %>
        <% @product.materials.each do |material| %>
          <div id='<%= material.name %>'><%= material.name %><input name="[single_quantities][]" class="input-quantity-form" 
           id="quantity-<%= material.id %>" value=<%= @product_materials.select{|hash| hash.material_id == material.id}[0].single_quantity %><%= material.quantity_unit %> ></div>
        <% end %>
      <% end %>
    </div>
      <%# javascriptのイベント発火により、ここに使用する食材のid情報を挿入する  %>
      <% if params[:"action"] == "edit" || params[:"action"] == "update" %>
        <% @product.materials.each do |material| %>
          <input name="product[material_ids][]" type="hidden" class="input-form" id=<%= material.id %>  value=<%= material.id %> > 
        <% end %>
      <% end %>
    <div class='guid-text' id='guid-text-options'>
      メモ
    </div>
    <%= form.text_area :options, class: 'options-form', placeholder: '255文字まで' %>
    <div class='input-btn-contents'>
      <label class='input-post'>
        <% if params[:"action"] == "new" || params[:"action"] == "create" %>
          <p class='post-text'>登録する</p>
          <%= form.submit '登録する', class: 'input-btn' %>
        <% end %>
        <% if params[:"action"] == "edit" || params[:"action"] == "update" %>
          <p class='post-text'>変更する</p>
          <%= form.submit '変更する', class: 'input-btn' %>
        <% end %>
      </label>
    </div>
  <% end %>
</div>

app/views/products/edit.html.erb
<div class='wrapper'>
  <div class='side-bar'>
    <%= render 'side_bar' %> 
  </div>
  <div class='materials-all'>
    <div class='guid-header'>
      料理に使う食材の画像をクリックしてください
    </div>
    <div class='materials-display'>
      <%= render 'shared/materials_display' %>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class='products-index-header'>
  <div class='catch-copy'>
    買い物を見通しよく
  </div>
  <div class='products-index-header-main'>
    <div class='products-index-page-title'>
      料理一覧
    </div>
    <div class='products-index-header-btns-wrapper'>
      <a href="/products/new" class='products-index-header-btn'>料理登録</a>
      <a href="/materials" class='products-index-header-btn'>食材一覧</a>
      <a href="/" class='products-index-header-btn'>献立一覧</a>
      <a href="/orders/show_summary" class='products-index-header-btn'>買い物リスト</a>
    </div>
  </div>
</div>
<div class='products-display'>
  <%= render 'shared/products_display' %>
</div>

app/views/products/new.html.erb
<div class='wrapper'>
  <div class='side-bar'>
    <%= render 'side_bar' %> 
  </div>
  <div class='materials-all'>
    <div class='guid-header'>
      料理に使う食材の画像をクリックしてください
    </div>
    <div class='materials-display'>
      <%= render 'shared/materials_display' %>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class='show-header'>
  <div class='show-page-title'>
    料理の詳細
  </div>
  <a href="/products" class='show-header-btn'>料理一覧<br>へ戻る</a>
</div>

<div class='show-information-wrapper'>
  <%= image_tag @product.image.variant(resize: '400x400'), class:'product-show-image' if @product.image.attached? %>
  <div class='product-name-wrapper'>
    <%= @product.name %>
  </div>
  <div class='product-sort-name-wrapper'>
    <%= @product.sort.name %>
  </div>
  <div class='material-names-label-text'>食材</div>
  <div class='product-materials-names-wrapper'>
    <% @product.materials.each do |material| %>
      <%= material.name %>
    <% end %>
  </div>
  <div class='manipulate-products-btns'>
    <%= link_to '編集する', edit_product_path(@product.id), class:'get-edit-page-btn' %>
    <%= link_to '削除する', product_path(@product.id), method: :delete, data: { confirm: '削除しますか？' }, class:'destroy-product-data-btn' %>
  </div>
</div>

app/views/shared/_material.html.erb
      <div class='material'>
        <div class='material-image-wrapper'>
          <div class="material-id" id='material-<%= material.id %>' aria-hidden='true'><%= material.id %></div> 
          <div class="material-quantity-unit" id='material-<%= material.quantity_unit %>' aria-hidden='true'><%= material.quantity_unit %></div>
          <%= image_tag material.image.variant(resize: '200x200'), class:'material-image' if material.image.attached? %>
          <% if params[:"controller"] == "materials" && params[:"action"] == "index" %>
            <ul class='manipulate-list' >
              <li>
                <%= link_to '編集', edit_material_path(material.id), class:'edit-material' %>
              </li>
              <li>
                <%= link_to '削除', material_path(material.id), method: :delete, data: { confirm: '削除しますか？' }, class:'destroy-material' %>
              </li>
            </ul>
          <% end %>
        </div>
        <div class='material-name-and-quantity-wrapper'>
          <div class='material-name' id='material-name'><%= material.name %></div>
          <% if params[:"action"] == "show_summary" %>
          <div class='material-quantity' id='material-quantity'><%= quantity %></div>
          <div class='show-summary-quantity-unit'><%= material.quantity_unit %></div>
          <% end %>
        </div>
      </div>

app/views/shared/_materials_all.html.erb
<div class='guid-header'>
<div>
<div class='materials-display'>
  <div class='category-name'>肉類・魚類・大豆製品</div>
  <div class='materials-wrapper'>
    <% @materials.where(category_id: 2).each do |material| %>
      <%= render partial: 'shared/material', locals: { material: material } %>
    <% end %>
  </div>
  <div class='category-name'>乳製品・海藻・小魚類</div>
  <div class='materials-wrapper'>
    <% @materials.where(category_id: 3).each do |material| %>
      <%= render partial: 'shared/material', locals: { material: material } %>
    <% end %>
  </div>
  <div class='category-name'>緑黄色野菜</div>
  <div class='materials-wrapper'>
    <% @materials.where(category_id: 4).each do |material| %>
      <%= render partial: 'shared/material', locals: { material: material } %>
    <% end %>
  </div>
  <div class='category-name'>淡色野菜・果物</div>
  <div class='materials-wrapper'>
    <% @materials.where(category_id: 5).each do |material| %>
      <%= render partial: 'shared/material', locals: { material: material } %>
    <% end %>
  </div>
  <div class='category-name'>穀類・芋類・砂糖類</div>
  <div class='materials-wrapper'>
    <% @materials.where(category_id: 6).each do |material| %>
      <%= render partial: 'shared/material', locals: { material: material } %>
    <% end %>
  </div>
  <div class='category-name'>油脂類</div>
  <div class='materials-wrapper'>
    <% @materials.where(category_id: 7).each do |material| %>
      <%= render partial: 'shared/material', locals: { material: material } %>
    <% end %>
  </div>
  <div class='category-name'>その他</div>
  <div class='materials-wrapper'>
    <% @materials.where(category_id: 8).each do |material| %>
      <%= render partial: 'shared/material', locals: { material: material } %>
    <% end %>
  </div>
</div>

app/views/shared/_materials_display.html.erb
  <% for i in 2..Category.data.size do %>
    <div class='category-name'><%= Category.data[i - 1][:name] %></div>
    <div class='materials-wrapper'>
      <% @materials.where(category_id: i).each do |material| %>
        <%= render partial: 'shared/material', locals: { material: material } %>
      <% end %>
    </div>
  <% end %>

app/views/shared/_product.html.erb
<div class='product'>
  <div class='product-image-wrapper'>
    <div class="product-id" id='product-<%= product.id %>' aria-hidden='true'><%= product.id %></div> 
    <%= image_tag product.image.variant(resize: '200x200'), class:'product-image' if product.image.attached? %> 
    <% if params[:controller] == "products" %>
      <%= link_to '詳細', product_path(product.id), class:'show-product' %>
    <% end %>
  </div>
  <div class='product-name' id='product-name'><%= product.name %></div>
</div>

app/views/shared/_products_display.html.erb
  <% for i in 2..Sort.data.size do %>
    <div class='sort-name'><%= Sort.data[i - 1][:name] %></div>
    <div class='products-wrapper'>
      <% @products.where(sort_id: i).each do |product| %>
        <%= render partial: 'shared/product', locals: { product: product } %>
      <% end %>
    </div>
  <% end %>